### ISSUE TITLE
Explore memgraph

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#1258]
**Please describe the feature**

As a developer, I want to explore if Memgraph can and should replace neo4j so that I can improve the graph DB performance given the same hardware.

**Acceptance Criteria**

- [ ] Try to replace neo4j with memgraph
- [ ] Perform benchmarks and write summary
- [ ] Create a new issue for implementation if viable
- [ ] The changes are in alignment with the privacy policy
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

Quick overview of Memgraph vs. neo4j here: https://memgraph.com/memgraph-for-neo4j-developers

**Comment by e0** [comment]
I have spent some time looking into memgraph today. Quite a few road blockers have already been discovered. Here is a summary of some of the findings so far.

## Highlights
### Docker compose
There is a docker image that is easy to work with. Alongside the other containers in `docker-compose-local.yml`, I added the following config and was able to spin up an instance of the memgraph platform. Note that the `--storage-properties-on-edges=true` is needed since its default value is `false, which prevents us from being able to store `stoichiometry` values.

```yaml

...  
  mg:
    image: "memgraph/memgraph-platform"
    ports:
      - "7688:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
      - ./neo4j/import:/usr/lib/memgraph/import
    environment:
      - MEMGRAPH="--storage-properties-on-edges=true"
    entrypoint: ["/usr/bin/supervisord"]

...

volumes:
  mg_lib:
  mg_log:
  mg_etc:
```
### Nice admin UI
The memgraph platform include an admin UI (called Memgraph Lab) that packs a lot of features and seems well designed. It is possible to run cypher queries, generate graph schemas, and it even has a dedicated page for datasets where one can explore and quickly import in public datasets shared by others.
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/423498/207386454-4bec0be6-80bc-49e5-b20e-519f206582fb.png">

### Uses the same `node.js` driver
Once running, the memgraph DB can be connected from `node.js` using the same library that is currently used (`neo4j-driver`). For more info, see: https://memgraph.com/docs/memgraph/2.4.0/connect-to-memgraph/drivers/nodejs

## Road blockers
- It seems like there is no support for apoc procedures, which are used frequently in the project. Source: https://discourse.memgraph.com/t/apoc-procedure-support-in-memgraph/33/2
- It doesn't seem to have (at least I didn't find any) any support for full text search
- While it is possible to import data using the admin UI, I didn't find a way to import data during build time.

## Syntax differences
Using contents of the `import.cypher` file, I was able to import some data using the admin UI. Some syntax needed to be slightly adjusted to work. Following are some differences. _Please note that I have not tested if the syntax required by memgraph works with neo4j._

### Create index
neo4j
```cypher
CREATE INDEX FOR (n:Metabolite) ON (n.id);
```

memgraph
```cypher
CREATE INDEX FOR (n:Metabolite) ON (n.id);
```

### Import data
neo4j
```cypher
LOAD CSV WITH HEADERS FROM "file:///FruitflyGemV1_2_0.metabolites.csv" AS csvLine
CREATE (n:Metabolite:FruitflyGem {id:csvLine.id});
```

memgraph
```cypher
LOAD CSV FROM "/usr/lib/memgraph/import/FruitflyGemV1_2_0.metabolites.csv" WITH HEADER AS csvLine
CREATE (n:Metabolite:FruitflyGem {id:csvLine.id});
```

## Summary
It was really easy to get started with an instance of the memgraph platform. Importing data was also quite straightforward after figuring out the syntax differences. Unfortunately there are some road blockers which make it difficult, or at least time consuming, to be able to quickly migrate from neo4j to memgraph.

This research could use a bit of follow-up to at least try rewriting a couple of queries without the need of apoc procedures. If it turns out that these rewritten queries are performant, it would make it more obvious that the lack of apoc procedure is not a hard road blocker.
